### ISSUE TITLE
Enhancement Request for the Autonomous Operator

### ISSUE THREAD

**Issue by karstengresch** [couchbaselabs/operator-sdk-tests#1]
Hi all,

as I couldn't find at least an umbrella project for the CB Autonomous Operator, I ask and please you to forward this TWIMC:

## Problem
When trying to install a `CouchbaseCluster` CR with the operator's UI only (!) on OpenShift, I get the following error message:

```
Danger alert:Error
Fix the following errors:

    Error "Required value" for field "spec.security.ldap.bindSecret".
```

And cannot proceed setting up the cluster.

When adding these resources manually:

**Secret**
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: cb-example-auth
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg==  # Administrator
  password: cGFzc3dvcmQ=          # password
```

**Bucket**
```yaml
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: default
spec:
  memoryQuota: 128Mi

```

**Cluster**
```yaml
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  image: couchbase/server:7.0.3
  security:
    adminSecret: cb-example-auth
  networking:
    exposeAdminConsole: true
    adminConsoleServices:
    - data
  buckets:
    managed: true
  servers:
  - size: 3
    name: all_services
    services:
    - data
    - index
    - query
    - search
    - eventing
    - analytics
```

**Route**
```yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: cb-ui
  namespace: cb09
  labels:
    app: couchbase
    couchbase_cluster: cb-example
    operator.couchbase.com/version: 2.3.2
spec:
  to:
    kind: Service
    name: cb-example-ui
  tls: null
  port:
    targetPort: couchbase-ui
```
, basically as per https://docs.couchbase.com/operator/current/howto-couchbase-create.html (the route added by me), I can setup the cluster without specifying a `spec.security.ldap.bindSecret` value.

## Desired behavior
After pressing the "Create Couchbase Cluster" button, pressing "Create" should create a Couchbase cluster with the bare minimum as per the Couchbase documentation for K8s. 

On OpenShift, an additional route shall be created.

In my perception, it is good practice to enable a working no-further-configuration-needed working minimum, namely for developer workflows.

Hope this is somehow useful for you.
